(define (problem HANOI-1-0)
(:domain HANOI)
(:objects P1 P2 P3 D1)
(:INIT (clear D1) 
	(onPic D1 P1) (picEmpty P2) (picEmpty P3) 
	(smaller D1 P1) (smaller D1 P2) (smaller D1 P3) 
	(handempty) )
(:goal (And (onPic D1 P3)))
)